// Run only against a disposable synthetic workspace. This test creates one project.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const requests=[];page.on('request',r=>{if(r.url().includes('/api/'))requests.push(r.url());});
if(!process.env.PILOT_WORKSPACE_TEST_URL)throw Error('Set PILOT_WORKSPACE_TEST_URL to a disposable two-project fixture; this test creates a project.');await page.goto(process.env.PILOT_WORKSPACE_TEST_URL);await page.locator('.project-header h1').waitFor();const projects=await page.locator('#project-select option').evaluateAll(ns=>ns.map(n=>({id:n.value,name:n.textContent})));console.log(projects);
await page.locator('a[href="#atlas"]').click();await page.locator('[data-key="atlas-service-question"]').fill('A project only draft');
await page.selectOption('#project-select',projects[1].id);await page.locator('.project-header h1').waitFor();await page.locator('a[href="#atlas"]').click();if(await page.locator('[data-key="atlas-service-question"]').inputValue()!=='')throw Error('A draft leaked to B');await page.locator('[data-key="atlas-service-question"]').fill('B draft');
await page.selectOption('#project-select',projects[0].id);await page.locator('.project-header h1').waitFor();if(await page.locator('[data-key="atlas-service-question"]').inputValue()!=='A project only draft')throw Error('A draft not restored');
await page.locator('a[href="#m2"]').click();if(await page.locator('[data-page="workflow"]').isVisible())throw Error('M1 visible in M2');await page.locator('[data-page="m2"]').getByText(/아직 지원하지/).waitFor();
await page.locator('a[href="#materials"]').click();await page.locator('.materials-slot').getByText(/저장 위치/).waitFor();
await page.locator('.stage-group summary').filter({hasText:'실험 설계'}).click();await page.locator('[data-key="stage:design"]').click();if(await page.locator('.detail-controls h2').textContent()!=='연구 기록')throw Error('wrong empty native node');await page.locator('[data-key="all-episodes"]').click();
await page.locator('[data-key="project-create-toggle"]').click();await page.locator('[data-key="new-project-name"]').fill('Browser created');await page.locator('[data-key="new-project-topic"]').fill('Browser synthetic topic');await page.locator('.project-create button[type="submit"]').click();await page.locator('.project-header h1').filter({hasText:'Browser synthetic topic'}).waitFor();
for(const theme of ['light','dark']){await page.selectOption('[data-key="theme-select"]',theme);for(const width of [320,390,768,1440,2560]){await page.setViewportSize({width,height:1000});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)throw Error('overflow '+width+' '+theme);}}
await page.setViewportSize({width:390,height:844});await page.locator('#nav-toggle').click();await page.locator('#project-select').waitFor({state:'visible'});await page.keyboard.press('Escape');await page.screenshot({path:process.env.PILOT_WORKSPACE_MOBILE_SCREENSHOT||'/tmp/workspace-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:process.env.PILOT_WORKSPACE_DESKTOP_SCREENSHOT||'/tmp/workspace-desktop.png'});
const unbound=requests.filter(u=>!new URL(u).pathname.startsWith('/api/projects')&&!new URL(u).searchParams.get('project'));console.log(JSON.stringify({errors,unbound,requests:requests.length,checks:'create, isolation/drafts, stage, unsupported milestones, materials, 10 layouts, mobile menu'}));if(errors.length||unbound.length)throw Error('browser errors or unbound requests');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
