// Read-only browser verification. Requires an existing public view fixture.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const out=process.env.PILOT_UI_OUTPUT||'output/evaluations/council-tabs';fs.mkdirSync(out,{recursive:true});let view=JSON.parse(fs.readFileSync(process.env.PILOT_UI_VIEW));
const council=view.councils.find(c=>c.node==='hypothesize'&&['disclosed_initials','disclosed_responses','disclosed_finals'].every(k=>c[k].length===3));assert.ok(council,'Need a disclosed three-round council');
const revision=view.revisions.find(r=>r.record.node===council.node&&r.record.attempt===council.attempt);const b=await chromium.launch();let writes=0,errors=[];
try{const p=await b.newPage({viewport:{width:1280,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.route('**/api/**',r=>{if(r.request().method()!=='GET'){writes++;return r.abort()}return r.request().url().includes('/api/view')?r.fulfill({json:view}):r.abort()});
await p.goto(process.env.PILOT_UI_URL||'http://127.0.0.1:8771');await p.getByRole('tab',{name:'단계와 대화',exact:true}).click();await p.locator(`[data-key="node:${council.node}"]`).click();await p.locator('[data-key=revision-select]').selectOption(revision.record.id);await p.locator('[data-key="tab:council"]').click();
if(await p.locator('[data-key=council-select]').count())await p.locator('[data-key=council-select]').selectOption(council.id);
const group=p.locator('#record-panel .council-discussion'),tabs=group.locator('[role=tab]');assert.equal(await tabs.count(),3);assert.equal(await group.locator('[role=tabpanel]:visible').count(),1);assert.equal(await group.locator('.statement[open]').count(),0);
const statement=group.locator('[role=tabpanel]:visible .statement').first();const key=await statement.getAttribute('data-key');const before=await statement.boundingBox();await statement.locator(':scope > summary').click();assert.ok((await statement.boundingBox()).height>before.height);assert.equal(await statement.locator('.statement-preview').isVisible(),false);const first=council.disclosed_initials[0].submission;assert.equal((await statement.locator(':scope > .council-paragraph').allTextContents()).join('\n\n'),first.rationale);
await tabs.nth(0).focus();await p.keyboard.press('ArrowRight');assert.equal(await tabs.nth(1).getAttribute('aria-selected'),'true');await p.keyboard.press('End');assert.equal(await tabs.nth(2).getAttribute('aria-selected'),'true');await p.keyboard.press('Home');assert.equal(await tabs.nth(0).getAttribute('aria-selected'),'true');assert.equal(await group.locator(`[data-key="${key}"]`).getAttribute('open'),'');
await tabs.nth(1).click();const response=group.locator('[role=tabpanel]:visible .statement').first();await response.locator(':scope > summary').click();const responseKey=await response.getAttribute('data-key');
// Only the browser fixture changes; no research write is sent.
await group.evaluate(n=>n.dataset.renderMarker='before-refresh');view={...view,head_id:view.head_id+'-ui-refresh'};await p.locator('.record-tools > details > summary').click();await p.locator('[data-key=refresh]').click();await p.waitForFunction(()=>{const n=document.querySelector('#record-panel .council-discussion');return n&&n.dataset.renderMarker!=='before-refresh'&&n.dataset.councilPhase==='response'});
assert.equal(await tabs.nth(1).getAttribute('aria-selected'),'true');assert.equal(await group.locator(`[data-key="${responseKey}"]`).getAttribute('open'),'');
const rows=[];for(const mode of ['light','dark']){await p.emulateMedia({colorScheme:mode});for(const width of [320,390,768,1280,1920,2560]){await p.setViewportSize({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await tabs.nth(0).click();const opened=group.locator('.statement[open]');await opened.evaluateAll(nodes=>nodes.forEach(n=>n.open=false));await group.scrollIntoViewIfNeeded();rows.push({mode,width});if(width===1280)await p.screenshot({path:`${out}/${mode}-collapsed.png`});}}
assert.equal(writes,0);assert.deepEqual(errors,[]);fs.writeFileSync(`${out}/verification.json`,JSON.stringify({layouts:rows,keyboard:true,originalText:true,refreshState:true,writes,errors},null,2));console.log({layouts:rows.length,keyboard:true,refreshState:true,writes});
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
